# We cannot enable container-based infrastructure for now since we need TeXlive
# from a PPA
#sudo: false
sudo: true
dist: trusty


# Work around travis bug:
# https://github.com/travis-ci/travis-ci/issues/4948#issuecomment-152839021
#language: generic
language: python

python:
    # Get python 2.7 back in once travis bug
    # <https://github.com/travis-ci/travis-ci/issues/4948> is solved.
    - '2.7'
    - '3.4'
    #- '3.5.0'

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install texlive-latex-base texlive-latex-extra
  - sudo apt-get -y install python-scipy python3-scipy  # for ImageHash
  - sudo apt-get -y install poppler-utils
  - sudo apt-get -y install pandoc
  - sudo apt-get -y build-dep python-matplotlib python3-matplotlib
  - sudo apt-get -y install python-setuptools python3-setuptools
  # Dependencies of Pillow, see
  # <https://pillow.readthedocs.org/en/latest/installation.html#linux-installation>.
  - sudo apt-get -y install libtiff5-dev libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python-tk
  - sudo apt-get -y install python-pytest python3-pytest
  - pip install pytest-cov

install:
  - sudo pip install -r requirements.txt
  # Alternative: setup.py install.
  # Using pip makes sure that the package is pip-compatible, too.
  - sudo pip install .

cache: pip

# manually install important TeX dependencies
before_script:
  - export TEXMFLOCAL=/tmp/texmf/ && mkdir -p $TEXMFLOCAL
  - wget http://mirrors.ctan.org/install/graphics/pgf/contrib/pgfplots.tds.zip -O /tmp/pgfplots.zip
  - unzip /tmp/pgfplots.zip -d $TEXMFLOCAL
  - texhash

# run tests
script:
  # cd into test directory to make sure we're using the pip-installed
  # matplotlib2tikz.
  - cd test
  - pytest --cov matplotlib2tikz

after_success:
  - bash <(curl -s https://codecov.io/bash)
