dist: trusty

language: python

python:
    - '2.7'
    - '3.6'

addons:
  apt:
    packages:
      - pgf
      - texlive-latex-base
      - texlive-latex-extra
      # for ImageHash
      - python-scipy
      - python3-scipy
      #
      - poppler-utils
      - pandoc
      # Dependencies of Pillow, see
      # <https://pillow.readthedocs.org/en/latest/installation.html#linux-installation>.
      - libtiff5-dev
      - libjpeg8-dev
      - zlib1g-dev
      - libfreetype6-dev
      - liblcms2-dev
      - libwebp-dev
      - tcl8.6-dev
      - tk8.6-dev
      - python-tk

before_install:
  - pip install pytest pytest-cov

install:
  - pip install -r test_requirements.txt
  - pip install .

cache: pip

# manually install important TeX dependencies
before_script:
  - export TEXMFLOCAL=/tmp/texmf/ && mkdir -p $TEXMFLOCAL
  - wget http://mirrors.ctan.org/install/graphics/pgf/contrib/pgfplots.tds.zip -O /tmp/pgfplots.zip
  - unzip /tmp/pgfplots.zip -d $TEXMFLOCAL
  - texhash

# run tests
script:
  # cd into test directory to make sure we're using the pip-installed
  # matplotlib2tikz.
  - cd test && MPLBACKEND=Agg pytest --cov matplotlib2tikz

after_success:
  - bash <(curl -s https://codecov.io/bash)
